### ISSUE TITLE
WLED crashes and reboots

### ISSUE THREAD

**Issue by arnaudov78** [Aircoookie/WLED#3634] opened 2024-01-02 14:08 UTC
### What happened?

Changing the  speed or density of effect "Fireworks Starburst" every time cause WLED to crash and reboot (Lost connection to device warning).

### To Reproduce Bug

Changing the  speed or density of effect "Fireworks Starburst" every time cause WLED to crash and reboot (Lost connection to device warning).

### Expected Behavior

Not to crash and reboot after effect speed changes

### Install Method

Binary from WLED.me

### What version of WLED?

0.14.1.b1  and 0.14.0 , the same

### Which microcontroller/board are you seeing the problem on?

ESP32

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment] 2024-01-02 19:41
Duplicate of #3609
Please use 0.14.1-b2 or newer.

**Closed by blazoncek** 2024-01-02 19:41 UTC
Labels: bug
