### ISSUE TITLE
aurora effect changing palletes to aurora

### ISSUE THREAD

**Issue by mehranviva** [Aircoookie/WLED#3383] opened 2023-09-23 14:35 UTC
### What happened?

when selecting the aurora effect the palletes changes to aurora

### To Reproduce Bug

.

### Expected Behavior

.

### Install Method

Binary from WLED.me

### What version of WLED?

WLED_0.14.0-b5_ESP8266

### Which microcontroller/board are you seeing the problem on?

ESP8266

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by softhack007** [comment] 2023-09-23 15:01
This 8s expected behaviour, as some effects have a preferred palette stored in their default parameters.
If you don't want to have these defaults, you can uncheck "Use effect default parameters" in UI settings.

Closing as not a bug.

**Closed** 2023-09-23 15:02 UTC
Labels: bug
