### ISSUE TITLE
Problem with preset numbers on iOS (13)

### ISSUE THREAD

**Issue by knochenkopp** [Aircoookie/WLED#348] opened 2019-11-13 13:19 UTC
The numbers 9 to 16 in the preset-circles are recognized as a part of a phone number in the iOS-App. They are blue and underlined. If I tap one preset in the row of 9 to 12, a window pops up on the bottom and say  "Call 9101112?". Same with the bottom row. If i tap a preset there the window pops up and say "Call 13141516"
The preset however will be executed.

![74819818_507857270071145_3329541635217293312_n](https://user-images.githubusercontent.com/13403544/68767092-64516f00-0620-11ea-93d3-58e434d5394b.jpg)

**Comment by Aircoookie** [comment] 2019-11-13 17:54
Thanks for the report :)
Closing as duplicate of #262

**Closed by Aircoookie** 2019-11-13 17:54 UTC

**Comment by knochenkopp** [comment] 2019-11-13 17:59
Darn! I searched multiple times for a duplicate report, still missed #262. XD
