### ISSUE TITLE
Hardware buttons / pushbuttons not active when ArtNet is active.

### ISSUE THREAD

**Issue by Stargaterunner** [Aircoookie/WLED#3556] opened 2023-11-28 11:05 UTC
I am looking for a solution to switch on/off using the shortcut command T=2 with hardware buttons for a LED matrix, if the data is coming via Artnet.  At the moment all hardware button commands are ignored if Artnet is active. 
When I use the WLED surface, on/off or dimming, this works.

WLED Version 0.14.0
Thanks for help.

**Comment by blazoncek** [comment] 2023-11-28 12:33
Live data (sACN/ArtNET/E1.31/DDP) takes precedence and cannot be switched off using On/Off button (or API command).

**Comment by blazoncek** [comment] 2024-06-19 14:33
Duplicate of #2915

**Closed by blazoncek** 2024-06-19 14:33 UTC
Labels: enhancement, wontfix
