### ISSUE TITLE
LED turns power on after reboot/power up

### ISSUE THREAD

**Issue by guergen1** [Aircoookie/WLED#2633] opened 2022-04-14 09:37 UTC
### What happened?

The LED turns on after reboot or powered up, the switch ist not on:
![grafik](https://user-images.githubusercontent.com/34395245/163357716-3bb5a966-ba52-4184-b34a-8175a8e32911.png)

### To Reproduce Bug

After downgrade to 0.13 b 1 it works fine

### Expected Behavior

The LED do not turn on!

### Install Method

Binary from WLED.me

### What version of WLED?

WLED 0.13.1 (build 2203150)

### Which microcontroller/board are you seeing the problem on?

ESP8266

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Aircoookie** [comment] 2022-04-14 09:51
Thanks for the report.
Do you have a boot preset configured?

**Comment by guergen1** [comment] 2022-04-14 12:00
No, there is no boot preset configured:
![grafik](https://user-images.githubusercontent.com/34395245/163386399-4f36351c-3bf2-4840-b7ef-997ae2c81af3.png)

**Comment by Cryptophunk** [comment] 2022-05-03 05:32
I've had this issue too. I've solved it temporary by setting a reboot schedule everyday using an external plug.

**Comment by modev92** [comment] 2022-05-06 05:35
I have this issue too, but defined one preset to have a different starting color. But the toggle: Turn Led on after power up/reset is off.

**Comment by RestOp** [comment] 2022-07-10 09:36
I have other begaviuor - i do NOT want to turn led on after power loss. But it turns on inspite of it!

**Comment by heyitsyang** [comment] 2022-11-22 02:08
I see the same thing but it happens when I restart Home Assistant also.  I have Turn on LEDs after boot/reset unchecked and I have a boot preset set.  If I restart Home Assistant, WLED turns on to the preset.

**Comment by R1DEN** [comment] 2023-01-31 08:58
have the same issue as @heyitsyang

**Comment by blazoncek** [comment] 2023-01-31 09:06
As a workaround create a preset with API `{"on":false}` and assign it as a boot preset.

**Closed by blazoncek** 2023-01-31 09:06 UTC
Labels: bug, workaround

**Comment by heyitsyang** [comment] 2023-01-31 12:52
I appreciate the tip about the workaround, but a workaround is not a fix.  Shouldn't this issue remain open?

**Comment by blazoncek** [comment] 2023-01-31 13:08
As a matter of fact I am unable to reproduce this kind of behaviour on 20+ of my devices. With or without boot presets or on/off toggle setting.
As such I deem problem not WLED related.

**Comment by RestOp** [comment] 2023-01-31 17:19
I had v11, now updated to last ( 0.13.3) - now works as expected! 
![image](https://user-images.githubusercontent.com/46259141/215835044-3c8ca969-79a1-47f2-96c6-71f9d6a48de5.png)
After disconettiong of power it blikns one time and then stays in OFF state.

Thanks a lot!

**Comment by marcolino7** [comment] 2023-10-15 12:16
Hi,
I have 4 node on version 0.14
One of this node do not power on leds on reboot, other yes. Same config, same boot preset on all 4 nodes.
Option to turn On led on after power up is unchecked. Something else I could verify?

Thanks

**Comment by jabber77** [comment] 2023-11-16 21:21
Hi, 
I have the same problem except that the problem appeared when I added the led strip to Home Assistant.
WLED version 0.13.3

**Comment by jabber77** [comment] 2023-11-16 21:26
Hi, 
I have the same problem except that the problem appeared when I added the led strip to Home Assistant
WLED version 0.13.3

**Comment by marcolino7** [comment] 2023-11-17 10:15
> Hi, I have the same problem except that the problem appeared when I added the led strip to Home Assistant. WLED version 0.13.3

Hi,
I use this startup preset and I fixed:

`{"on":false,"bri":128,"transition":7,"mainseg":0,"seg":[{"id":0,"start":0,"stop":1,"grp":1,"spc":0,"of":0,"on":true,"frz":false,"bri":255,"cct":127,"set":0,"col":[[127,172,255,0],[0,0,0,0],[0,0,0,0]],"fx":0,"sx":128,"ix":128,"pal":0,"c1":128,"c2":128,"c3":16,"sel":true,"rev":false,"mi":false,"o1":false,"o2":false,"o3":false,"si":0,"m12":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0},{"stop":0}]}`

**Comment by raspberrycoulis** [comment] 2024-04-25 07:37
I have this issue, running 13.3 as anything newer seems to mess up WiFi connectivity. 

Basically, fresh install on an ESP8266 with 100 LED's connected, the turn LED's on by default is unchecked and preset is set to 0. However a reboot causes the LED's to power up still!

Have Home Assistant configured too, so tried removing the node from there in case it was linked (as others have mentioned) but still have the issue. 

Any more ideas as to why this is happening?

**Comment by blazoncek** [comment] 2024-04-25 08:01
The only change (if needed) will happen in 0.15 or newer so you will need to upgrade unfortunately.

**Comment by raspberrycoulis** [comment] 2024-04-25 08:05
> The only change (if needed) will happen in 0.15 or newer so you will need to upgrade unfortunately.

Hmm ok. Since 0.14 my devices all become unresponsive. On the off chance the UI does partially load, there are browser console errors with things failing to load or the device loses connection to the LED's.

I may test a beta 0.15 and see what happens.

**Comment by DedeHai** [comment] 2024-10-05 09:30
> The option "Turn LEDs on after power up/reset" shoud be independant of the preset.

I disagree. Apply preset at boot means that it applies that preset at boot. If you want that preset not to turn on the LEDs, do as you proposed (on:false)

**Comment by markusressel** [comment] 2024-12-13 14:22
I want to change the brightness and color using a preset, but not affect the "on"/"off" state, because a PIR Sensor is controlling this. However, even when removing the "n´on" state, as you suggest, the light still turns on.

I cannot remove the "brightness" property because I need to control that even when the light is off. Is there a way to do this?

**Comment by blazoncek** [comment] 2024-12-13 16:06
@markusressel see [KB](https://kno.wled.ge/interfaces/json-api/).

You are not doing it right. Anything, including what you request, is possible by correctly utilising JSON API.

**Comment by markusressel** [comment] 2024-12-13 17:36
@blazoncek I don't have access to the API because I only have the device itself. But I guess I am " not doing it right" by wanting to have a device that works on its own. Thanks anyway for the useless response 👌

For anyone interested: This is easily possible using ESPHome and that's what I am have done now. WLED is fine for simple usage (and API usage apparently), but on device seems to be lacking. Love to both of them, cheers.

**Comment by blazoncek** [comment] 2024-12-13 18:44
Apparently you do not want to learn. Sorry.

BTW anyone has access to JSON API. In fact everything is driven by JSON API including UI and external and internal actions. Just look into preset - that's your JSON API.
