### ISSUE TITLE
WLED Feature Request: Improved Number Font

### ISSUE THREAD

**Issue by Michaelnorge** [Aircoookie/WLED#3885] opened 2024-04-06 12:00 UTC
Hi!

While the current WLED font works well for large text, the small numbers appear visually unbalanced.
To improve this, I propose: Proportional scaling: Numbers scale proportionally with text size for better harmony.

**Comment by blazoncek** [comment] 2024-04-06 13:13
Duplicate of #3071

**Closed by blazoncek** 2024-04-06 13:13 UTC
Labels: enhancement
