### ISSUE TITLE
WS2805 Support

### ISSUE THREAD

**Issue by SimonG2024** [Aircoookie/WLED#3776] opened 2024-02-26 14:40 UTC
WS2805 doesn't exist yet and that would be great if it can be added. You can do RGBCCT with them and I think it would be great for others to have support

**Comment by blazoncek** [comment] 2024-02-27 11:51
Perhaps in 0.16, so not soon.

**Comment by davidmehren** [comment] 2024-03-06 17:59
Duplicate of https://github.com/Aircoookie/WLED/issues/3608 ?

**Comment by blazoncek** [comment] 2024-03-06 18:48
Indeed.

**Closed by blazoncek** 2024-03-06 18:48 UTC
Labels: enhancement

**Comment by blazoncek** [comment] 2024-03-24 20:02
Implemented for 0.15.0-b2
