### ISSUE TITLE
Indexing the channels on WS2811 as if there were 3 separate leds.

### ISSUE THREAD

**Issue by ThisAccount7777** [Aircoookie/WLED#3379] opened 2023-09-20 00:59 UTC
**Is your feature request related to a problem? Please describe.**
Hardware limitations - read context for more info.

**Describe the solution you'd like**
Index each channel on the addressable led chips like WS2811/WS2814 as a separate led/index
eg.
[ic: 1, channel: r, index: 1], [ic: 1, channel: g, index: 2], [ic: 1, channel: b, index: 3], [ic: 2, channel: r, index: 4], [ic: 2, channel: g, index: 5]

**Describe alternatives you've considered**
74HC595 and Arduino (limited control over leds) or one WS2811 per led

**Additional context**
![image](https://github.com/Aircoookie/WLED/assets/145419488/0aa57312-4182-431c-b63e-0068555f6e17)
Suppose you are are trying to control 6 LEDS but there isn't enough room on the PCB to accommodate all the chips. 
Note that this is an EXAMPLE circuit so it wouldn't work. The final version will have 21 leds.

**Comment by blazoncek** [comment] 2023-09-20 04:45
Implemented as WS2811 White (type 19) in LED settings. If this does not satisfy your requirements you will need to re-implement yourself.
Duplicate of #3378, closing.

**Closed by blazoncek** 2023-09-20 04:45 UTC
Labels: enhancement

**Comment by blazoncek** [comment] 2023-09-20 11:59
Using "WS2811 White" LED type controls each channel ow WS2811 chip as a separate white (or any color) single pixel (index) LED.
This is exactly what you are describing.

**Comment by ThisAccount7777** [comment] 2023-09-21 00:55
Control each channel on any addressable led driver ic as a single addressable LED*

**Comment by softhack007** [comment] 2023-09-21 10:23
> Control each channel on any addressable led driver ic as a single addressable LED*

@ThisAccount7777 the only difference between your last statement and the conclusion from @blazoncek is "WS281x chip" vs "any addressable led IC". For me this sound like the same thing, please clarify if I misunderstood.

I've seen the complaints in discord about "MODs keep closing my request because they do not understand". So you need to help us understand.

I you are looking for something different than what we already have, there is some homework for you :
* try "WS2811 White" on your hardware
* summarize how the behaviour differs from what you are looking for.

Then we have a basis for discussion.

**Comment by softhack007** [comment] 2023-09-21 10:27
Maybe for additional  clarification: 
WLED communicates with the ws281x IC, but it cannot "see" or control anything behind the IC. So it's possible to "abuse" R/G/B color and treat then as three different "white" items. But in case that each ws2811 has several LEDs attached to each color output (like most ws2811 control 3 leds at once) this is something we cannot change.

**Comment by ThisAccount7777** [comment] 2023-09-22 01:12
I might have to try again on a physical setup with WS2811 white mode.
