### ISSUE TITLE
Incorrect Light Capabilities set when LED strips is only On/Off

### ISSUE THREAD

**Issue by frenck** [Aircoookie/WLED#2979] opened 2022-12-27 22:34 UTC
### What happened?

When configuring the WLED strip with a single segment, only providing On/Off capabilities, WLED will determine its Light capabilities = 1 = RGB Light.

![image](https://user-images.githubusercontent.com/195327/209728714-dab1bd5c-c235-4476-a9a7-c5f5b2c310f2.png)

Dump from the `wled` Python library from the configured light:

Led info:
`
Leds(cct=False, count=1, fps=3, light_capabilities=<LightCapability.RGB_COLOR: 1>, max_power=850, max_segments=16, power=137, rgbw=False, wv=False, segment_light_capabilities=[<LightCapability.RGB_COLOR: 1>])
`

Segment state:
`
Segment(brightness=255, clones=-1, color_primary=(255, 160, 0), color_secondary=(0, 0, 0), color_tertiary=(0, 0, 0), effect=Effect(effect_id=0, name='Solid'), intensity=128, length=1, on=True, palette=Palette(name='Default', palette_id=0), reverse=False, segment_id=0, selected=True, speed=128, start=0, stop=1)
`

### To Reproduce Bug

Use the following configuration

![image](https://user-images.githubusercontent.com/195327/209728585-26f12c9f-5e5e-44f2-b6f9-5a5a2fdcefd5.png)

### Expected Behavior

Not to have RGB controls and communicate a Light Capability value of `0`.

### Install Method

Binary from WLED.me

### What version of WLED?

0.14.0-b1

### Which microcontroller/board are you seeing the problem on?

ESP8266

### Anything else?

Found during testing/updating Home Assistant with LC support in PR: https://github.com/home-assistant/core/pull/75248

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment] 2022-12-28 07:02
@frenck can you confirm latest commit fixes the issue?

**Comment by frenck** [comment] 2022-12-28 09:07
I'm happy to confirm it on the next binary that is shipped? 🤷

**Comment by ezcGman** [comment] 2023-01-04 23:02
Just tested it with the latest master and the issue is resolved:
![image](https://user-images.githubusercontent.com/3090131/210666187-6e255be4-cb4d-4c57-9ca7-61de22762a50.png)
![image](https://user-images.githubusercontent.com/3090131/210666252-feba4585-261c-4b8f-95c6-60cc58ee875c.png)

**Comment by blazoncek** [comment] 2023-01-05 06:23
If it is ok, please close.

**Comment by frenck** [comment] 2023-01-05 07:00
The HA release went out the door yesterday, meaning I have some time again. Will try to confirm today and close if resolved

**Comment by PaoloTK** [comment] 2023-02-01 21:41
> The HA release went out the door yesterday, meaning I have some time again. Will try to confirm today and close if resolved

Hi, any progress on this? Thank you.

**Comment by blazoncek** [comment] 2023-04-24 09:20
@frenck any updates? It has been a while...

**Comment by blazoncek** [comment] 2023-05-27 13:49
Closing as there is no feedback and the modification was made.

**Closed by blazoncek** 2023-05-27 13:49 UTC
Labels: bug
