### ISSUE TITLE
APA102 strip breaks ethernet communication

### ISSUE THREAD

**Issue by nwalke** [Aircoookie/WLED#2879] opened 2022-11-11 17:19 UTC
### What happened?

When saving an APA102 LED strip configuration, QuinLED-ESP32 ethernet no longer communicates but continues to show as connected.  Prior to saving an LED strip configuration with an APA102 LED ethernet communication works just fine.

### To Reproduce Bug

Run 0.13.3, get ethernet set up and connected, verify connection is working with both wifi and ethernet.  Add a strip of APA102 to your LED configuration, ethernet will no longer communicate.  You can still talk to WLED using wifi.

### Expected Behavior

Ethernet would continue to function after adding an APA102 strip.

### Install Method

Self-Compiled

### What version of WLED?

WLED 0.13.3 build 2209222

### Which microcontroller/board are you seeing the problem on?

ESP32

### Relevant log/trace output

```shell
rst:0xc (SW_CPU_RESET),boot:0x12 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0018,len:4
load:0x3fff001c,len:1044
load:0x40078000,len:8896
load:0x40080400,len:5816
entry 0x400806ac

---WLED 0.13.3 2208222 INIT---
esp32 v3.3.6-16-gcc5440f6a2
heap 294960
PIN ALLOC: Pin 1 allocated by 0x89 (137)
Registering usermods ...
Reading config
Reading settings from /wsec.json...
JSON buffer released. (3)
Reading settings from /cfg.json...
initE: Attempting ETH config: 4
PIN ALLOC: Pin 21 allocated by 0x81 (129)
PIN ALLOC: Pin 19 allocated by 0x81 (129)
PIN ALLOC: Pin 22 allocated by 0x81 (129)
PIN ALLOC: Pin 25 allocated by 0x81 (129)
PIN ALLOC: Pin 26 allocated by 0x81 (129)
PIN ALLOC: Pin 27 allocated by 0x81 (129)
PIN ALLOC: Pin 23 allocated by 0x81 (129)
PIN ALLOC: Pin 18 allocated by 0x81 (129)
PIN ALLOC: Pin 5 allocated by 0x81 (129)
PIN ALLOC: Pin 17 allocated by 0x81 (129)
initC: *** Ethernet successfully configured! ***
Removing all.
PIN ALLOC: Pin 16 allocated by 0x82 (130)
Successfully inited strip 0 (len 254) with type 22 and pins 16,255 (itype 17)
Starting usermod config.
JSON buffer released. (1)
Initializing strip
Usermods setup
Access point disabled.
Connecting to mywifi...

Connected! IP address: 192.168.1.87
Init STA interfaces
mDNS started
FileRead: /index.htm
Not-Found HTTP call:
URI: /skin.css
FileRead: /skin.css
JSON buffer size: 3998
JSON buffer released. (17)
Not-Found HTTP call:
URI: /presets.json
FileRead: /presets.json
JSON buffer released. (12)
settings resp1
---DEBUG INFO---
Runtime: 30000
Unix time: 30,000
Free heap: 167416
Wifi state: 3
State time: 0
NTP last sync: 999000000
Client IP: 192.168.1.87
Loops/sec: 2394
Max UM time[ms]: 1
Local time: 00:01
---DEBUG INFO---
Runtime: 60005
Unix time: 60,005
Free heap: 167416
Wifi state: 3
State time: 0
NTP last sync: 999000000
Client IP: 192.168.1.87
Loops/sec: 2146
Max UM time[ms]: 1
ETH ConnectedDisconnected!
Access point disabled.
Connecting to mywifi...
Access point disabled.
Connecting to mywifi...

Connected! IP address: 192.168.1.90
Init STA interfaces
mDNS started
Disconnected!
Access point disabled.
Connecting to mywifi...
Access point disabled.
Connecting to mywifi...

Connected! IP address: 192.168.1.90
Init STA interfaces
mDNS started
---DEBUG INFO---
Runtime: 90010
Unix time: 90,010
Free heap: 166316
Wifi state: 3
State time: 0
NTP last sync: 999000000
Client IP: 192.168.1.90
Loops/sec: 2177
Max UM time[ms]: 1
FileRead: /index.htm
Not-Found HTTP call:
URI: /skin.css
FileRead: /skin.css
JSON buffer size: 3998
JSON buffer released. (17)
Not-Found HTTP call:
URI: /presets.json
FileRead: /presets.json
JSON buffer released. (12)
FileRead: /favicon.ico
settings resp1
settings resp1
Local time: 00:02
---DEBUG INFO---
Runtime: 120015
Unix time: 120,015
Free heap: 166248
Wifi state: 3
State time: 0
NTP last sync: 999000000
Client IP: 192.168.1.90
Loops/sec: 2156
Max UM time[ms]: 1
settings resp2
JSON buffer released. (6)
Not-Found HTTP call:
URI: /win
API req: /win
JSON buffer size: 1755
JSON buffer released. (17)
JSON buffer released. (12)
FileRead: /favicon.ico
Not-Found HTTP call:
URI: /win
API req: /win
Not-Found HTTP call:
URI: /win
API req: /win
---DEBUG INFO---
Runtime: 150020
Unix time: 150,020
Free heap: 166244
Wifi state: 3
State time: 0
NTP last sync: 999000000
Client IP: 192.168.1.90
Loops/sec: 2158
Max UM time[ms]: 1
Local time: 00:03
---DEBUG INFO---
Runtime: 180025
Unix time: 180,025
Free heap: 166244
Wifi state: 3
State time: 0
NTP last sync: 999000000
Client IP: 192.168.1.90
Loops/sec: 2173
Max UM time[ms]: 1
No data.
Re-init busses.
Removing all.
Digital Cleanup.
PIN ALLOC: Pin 16 allocated by 0x82 (130)
PIN ALLOC: Pin 3 allocated by 0x82 (130)
Successfully inited strip 0 (len 254) with type 51 and pins 16,3 (itype 29)
PIN ALLOC: Pin 2 allocated by 0x82 (130)
PIN ALLOC: Pin 4 allocated by 0x82 (130)
Successfully inited strip 1 (len 557) with type 51 and pins 2,4 (itype 30)
Writing settings to /wsec.json...
JSON buffer released. (4)
Writing settings to /cfg.json...
JSON buffer released. (2)
FileRead: /index.htm
Not-Found HTTP call:
URI: /skin.css
FileRead: /skin.css
JSON buffer size: 3998
JSON buffer released. (17)
Not-Found HTTP call:
URI: /presets.json
FileRead: /presets.json
JSON buffer released. (12)
---DEBUG INFO---
Runtime: 210030
Unix time: 210,030
Free heap: 163124
Wifi state: 3
State time: 0
NTP last sync: 999000000
Client IP: 192.168.1.90
Loops/sec: 2299
Max UM time[ms]: 1
```

### Anything else?

In my serial log output you can see when I connect ethernet it gets an ip of 192.168.1.90.  At that point, communication via that IP works perfectly well and I can continue to also use 192.168.1.87.  Once I tried saving with two strips of APA102 (`Successfully inited strip 1`) communication via 192.168.1.90 no longer works.  The ethernet hat's lights are still lit and blinking as if there's communication, but you can't actually get to it.

Happy to do any further debugging, just would need to know what flags to enable as it still shows as connected to ethernet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment] 2022-11-11 17:26
Duplicate of #2542 
Closing.

**Closed by blazoncek** 2022-11-11 17:26 UTC
Labels: bug
