### ISSUE TITLE
Slider Annoyance on Phone

### ISSUE THREAD

**Issue by Doyle4** [Aircoookie/WLED#1400] opened 2020-11-30 12:40 UTC
**Describe the bug**
Using color slider changes webpage

**To Reproduce**
Slide the color slider

**Expected behavior**
To choose colors with slider without it going it going to home page or effects page if sliding to the right.

**WLED version**
 - Board: Doesn't matter
 - Version 11
 - Format Binary

**Additional context**
Possible to have the bottom row, color, effects etc to not accept "swipes" out of their command zone (don't know how else to describe it sorry), when not hovering over them, any swipes on the screen do not interfere with them.

Thank you for your help!

**Comment by Legsmaniac** [comment] 2020-11-30 14:34
Hmmmmm.  I cannot reproduce this.

**Comment by Aircoookie** [comment] 2020-11-30 14:43
Thank you for the report!
Could not reproduce it either yet, does this happen with the sliders underneath the color wheel or with the optional RGB sliders? What is your phone model/browser/app?

**Comment by Doyle4** [comment] 2020-11-30 15:14
Trying to upload a video, will try when home.
Googlechrome on iPhone :)

**Comment by Doyle4** [comment] 2020-11-30 15:16
I think I know what it is, my finger is touching the outside of the colour slider box and moving across to different section

**Comment by huggy-d1** [comment] 2020-11-30 16:06
Try using one of those touch sensitive pen tops (often black & foam-like).

**Comment by allgoewer** [comment] 2020-12-07 22:29
I notice the same issue on a Pixel 4a running Android 11, in the WLED-App (1.03) as well as in Chrome (87.0.4280.86)
See https://www.youtube.com/watch?v=vkNUljU3Rk4

It seems not to happen with the white-channel slider

**Comment by Doyle4** [comment] 2020-12-07 22:49
So glad someone else has spotted it! It keeps happening and I thought it was me.

**Comment by allgoewer** [comment] 2020-12-08 11:46
I think I found the issue.

This patch https://github.com/Aircoookie/WLED/blob/ac010cd7b21cba8e2d91d01ca6a100050879e248/wled00/data/index.htm#L1128 seems to update iro.js

If you blame this line with a previous version, you'll notice that the [lock()](https://github.com/Aircoookie/WLED/blame/362156c8abb6f4580ff2edff8b49a651e946c0ab/wled00/data/index.htm#L2025) function checks for some classes provided by iro.js, but it seems as these names changed.

I'll try to fix it and create a pull request later.

**Comment by Doyle4** [comment] 2020-12-08 11:57
Keeping an eye on this as its driving me mad, few customers with devices I have made are complaining of it also. Told them a patch is coming soon.

**Comment by JCPTECH** [comment] 2020-12-09 03:07
I am also getting this issue. for colour wheel and sliders. How to patch this issue?

**Comment by allgoewer** [comment] 2020-12-09 07:26
Well, you could

* Go back to v0.10.x
* Wait for my PR to be merged into (hopefully) the next patch release
* Build an image with my patch yourself

**Closed** 2020-12-09 13:08 UTC
Labels: bug

**Comment by Doyle4** [comment] 2020-12-09 21:48
Thanks for looking into this @allgoewer and thanks @Aircoookie also :) 

Great team and support.
