### ISSUE TITLE
Syntax Error: Bad control character in string literal in JSON at position 3006 (line 1 column 3007)

### ISSUE THREAD

**Issue by KitHubek** [Aircoookie/WLED#3646] opened 2024-01-05 20:08 UTC
### What happened?

Go to browser, WLED instance IP and loading interface (PC mode) and... bottom error: 

Syntax Error: Bad control character in string literal in JSON at position 3006 (line 1 column 3007)

![wledERROR](https://github.com/Aircoookie/WLED/assets/91805313/f9c0bb17-a688-4f88-ac1d-74ad83554944)

### To Reproduce Bug

i dont know, just go to www IP web control WLED

### Expected Behavior

no error

### Install Method

Binary from WLED.me

### What version of WLED?

WLED 0.14.0 (build 2310130)

### Which microcontroller/board are you seeing the problem on?

ESP8266

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment] 2024-01-05 23:39
Duplicate of #3641

**Closed by blazoncek** 2024-01-05 23:39 UTC
Labels: bug
