### ISSUE TITLE
Can't populate 12x2 Panels with 8x8 Pixel each

### ISSUE THREAD

**Issue by DarthWeber** [Aircoookie/WLED#3495] opened 2023-10-31 14:09 UTC
### What happened?

I am trying to define an array of 12x2 panels with 8x8 dimesnion each, but it fails with the generator as well as manual defining.

- when i enter 24 panels i only get 0-22, 23 is missing. After adding it again, it is messed after save
- the generator also  fails, maybe due to this bug.

12x1 seems to work as expected

### To Reproduce Bug

define 24 panels with 8x8 each, i let the orientation unchanged. In the "Matrix generator" enter 12 horizontal and 2 vertical.

### Expected Behavior

as defined

### Install Method

Self-Compiled

### What version of WLED?

WLED 0.14.0

### Which microcontroller/board are you seeing the problem on?

ESP32

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment] 2023-10-31 14:50
Duplicate of #3295
Closing.

**Closed by blazoncek** 2023-10-31 14:50 UTC
Labels: bug
