### ISSUE TITLE
Single LED Control Bug

### ISSUE THREAD

**Issue by bad-jesus** [Aircoookie/WLED#2664] opened 2022-05-10 00:19 UTC
### What happened?

I think there is a bug in single LED control. 

This string should only light up bulb ID 2 with colour RGB(0,213,255)
But I actually have bulb ID 2 and 3 lit up this colour. 
All other bulbs in my segment string should be RGB(0,255,30) and they are except that bulb id 3 is rgb(0,213,255)

Let's use this string : 
{"seg":[{"id":0,"i":[0,2,["0","0","255"],3,4,["255","255","255"],5,47,["0","0","255"]]}]}

It should be LED IDs 0-2 are Blue, LEDs 3-4 are white, LEDs 5-47 are blue. 

INstead, what I have is LEDs 0-1 are blue, 2 is off, 3 is white, 4 is off, 5-47 are blue. 

This example is just using one segment, but we are testing with multiple segments as well. 
Similar issues, and more issues are occuring. 

It would also be amazing if this single LED feature had a way to bypass all segments.
This is anecdoatal at this point, but it does seem to always be an issue when the ranges are just 2 bulbs. 

So 1-2 seems to be the glitch. We are doing some more testing around this, but that is what it seems to be. You can't have a 2 bulb range?
badjesus — Today at 3:32 PM
{"seg":[{"id":0,"i":[0,3,["255","0","0"],4,["0","0","255"],5,["255","255","255"],6,["0","255","0"],7,11,["255","0","0"]]}]}

In this example : 

LED's 0-2 are RED, 3 is off, then 4 is BLUE, 5 is white, 6 is green, 7-11 are red

What it shoudl be is 

0-3 RED, 4 BLUE, 5 WHITE, 6 GREEN, 7-11 RED

It seems to be when a single bulb is active AFTER a range that this happens. Almost like there is just a typo on the index because light 1 = index 0? 

Basically, we continually are getting the bulb lit up that we want to be that colour, and the bulb before it also. 

So in this example, only bulb 11 should be white. 

BUt bulb 10 and 11 are white
{"seg":[{"id":0,"i":[0,10,["0","0","255"],11,["255","255","255"],12,47,["0","0","255"]]}]}

### To Reproduce Bug

It is important to be able to recreate this though, that this is done in series. So we are sending commands like this : 

{"seg":[{"id":0,"i":[0,8,["0","0","255"],9,["255","255","255"],10,47,["0","0","255"]]}]}
{"seg":[{"id":0,"i":[0,9,["0","0","255"],10,["255","255","255"],11,47,["0","0","255"]]}]}
{"seg":[{"id":0,"i":[0,10,["0","0","255"],11,["255","255","255"],12,47,["0","0","255"]]}]}
{"seg":[{"id":0,"i":[0,11,["0","0","255"],12,["255","255","255"],13,47,["0","0","255"]]}]}
{"seg":[{"id":0,"i":[0,12,["0","0","255"],13,["255","255","255"],14,47,["0","0","255"]]}]}
{"seg":[{"id":0,"i":[0,13,["0","0","255"],14,["255","255","255"],15,47,["0","0","255"]]}]}

This is all with a delay in between, but we are sending these commands. It seems that it is remembering the previous state of the last bulb that is in the first range and it is not being over-written. So we end up getting 2 white bulbs instead of 1. 

To bandaid it for now, in between each command we are setting a reset like this. 

{"seg":[{"id":0,"i":[0,8,["0","0","255"],9,["255","255","255"],10,47,["0","0","255"]]}]}
{"seg":[{"id":0,"i":[0,47,["0","0","255"]]}]}
{"seg":[{"id":0,"i":[0,9,["0","0","255"],10,["255","255","255"],11,47,["0","0","255"]]}]}

I should also add that on multiple occasions, sending a slightly incorrect command with this will actually reset our segments and over-write them.  We found a way around this but it hasn't been stress tested yet.

### Expected Behavior

The expected behavior is as per the documentation, it should allow any type of range and not randomly light up the last LED in that range, before a single ID, not in a range. 

### Install Method

Binary from WLED.me

### What version of WLED?

0.13.1

### Which microcontroller/board are you seeing the problem on?

ESP32

### Relevant log/trace output

```shell
I can get this if required. I haven't looked into how to do this yet. I see the log, but it is empty so I am sure I need to turn this one somewhere first.
```

### Anything else?

I would be happy to explain in more detail if required. I can also provide video information. 

This was tested using multiple methods to fire to the API including a custom UI but this issue also occurs with a stock WLED install and using postman to send the commands. 

The entire controller hardware running for this test is Quinn's latest (I think v3) digi uno and wled shield, but we tried it on other custom hardware as well with teh same result. 

The IC we are using is SK6812_RGBW in teh settings, but we are actually connecting to UCS2904B IC type (same SPI output as SK6812_RGBW but we are at 12v not 5v)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment] 2022-07-22 19:50
Sorry for late response. This was low on priority tasks.
First, numeric values for colors have to be without quotes like [0,0,255] not ["0","0","255"].
Second, stop indexes are not inclusive, so `"i":[0,2,...]` means LEDs 0 and 1 only (consider mathematical set formulation like [0,2), where 0 is included and 2 is not).

Perhaps this would need a better description in [knowledge base](https://github.com/Aircoookie/WLED-docs) and you are welcome make contribution there if you wish.

Closing since behaviour is tested and functions as designed.

**Closed by blazoncek** 2022-07-22 19:50 UTC
Labels: bug
