### ISSUE TITLE
White balance on WS2812B strips does not work with UDP Realtime

### ISSUE THREAD

**Issue by alexanderp4580** [Aircoookie/WLED#3243] opened 2023-06-11 22:56 UTC
### What happened?

The White Balance correction feature works great with built in effects to fix unpleasant blue color when full white is used.

However when using realtime UDP the configured white balance setting is not applied.

I apologize if this is a feature request and not a bug.

A suggestion of how to fix this would be enough for me to create a PR.

Thank you.

### To Reproduce Bug

Use RGB strip with white balance correction and send UDP (DRGB) full white to WLED.

### Expected Behavior

White balanced RGB color should be displayed, exactly the same as normal effects.

### Install Method

Self-Compiled

### What version of WLED?

0.13.3

### Which microcontroller/board are you seeing the problem on?

ESP32

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment] 2023-06-12 05:24
You will need to adjust white balance in your UDP realtime data sender (whichever that is).
This being due to the fact that WLED does not know the intent of the received RGB values or the actual color temperature of attached LEDs.
Closing as this is not a bug neither a feature that can be implemented without unwanted consequences.

**Closed by blazoncek** 2023-06-12 05:24 UTC
Labels: enhancement, wontfix
