### ISSUE TITLE
Per GPIO inverse functionality

### ISSUE THREAD

**Issue by serhat-ozkara** [Aircoookie/WLED#3325] opened 2023-08-16 08:36 UTC
**Is your feature request related to a problem? Please describe.**
I installed WLED to one of my CCT bulbs. However since I can't inverse one of the GPIO's, it's not working correctly.
**Describe the solution you'd like**
GPIO selection could be inversed by not a checkbox but by gpio number * -1 Ex: GPIO -2 could be inverse GPIO2

**Describe alternatives you've considered**

**Additional context**

Thank you for your ideas for making WLED better!

**Comment by blazoncek** [comment] 2023-08-16 08:49
Duplicate of  #1971 
Closing

**Closed by blazoncek** 2023-08-16 08:49 UTC
Labels: enhancement
