### ISSUE TITLE
Athom 15w led bulb fade on startup

### ISSUE THREAD

**Issue by koen-serneels** [Aircoookie/WLED#4032] opened 2024-06-21 22:10 UTC
I have a Athom 15w led bulb and flashed the latest stable 0.14.4. When the bulb starts ootb it has a warm white color with low brightness. I created a preset for the color I actually want and configured it to startup using that preset. However, at cold start the bulb first seems to show to the default color (it does that instantly without fading or anything) and like a couple of hundred msecs later it seems to change to the preset, this change is done using fading. This gives a bit of a clunky effect where the led instantly turns on to a non desired light setting and then starts to gently fade to the desired color. Is it possible to let the led start completely off and directly start with fading to the configured preset?

**Comment by blazoncek** [comment] 2024-06-22 08:35
Please set the transition time to 0 for boot preset.

**Comment by blazoncek** [comment] 2024-06-26 09:58
Please close the issue if the workaround works, otherwise please provide an update.

**Comment by Andro-Marian** [comment] 2024-07-01 19:31
Not working for my. I set the "Turn LEDs on after power up/reset" to off, "Default brightness" to 0, Preset to 1.

Still wakes up as Orange color then starting to change to red.

`{"on":true,"bri":128,"transition":0,"mainseg":0,"seg":[{"id":0,"grp":1,"spc":0,"of":0,"on":true,"frz":false,"bri":255,"cct":127,"col":[[255,0,0,0],[0,0,0,0],[0,0,0,0]],"fx":0,"sx":128,"ix":128,"pal":0,"c1":128,"c2":128,"c3":16,"sel":true,"rev":false,"mi":false,"o1":false,"o2":false,"o3":false,"si":0,"m12":0}]}`

**Comment by Jusius** [comment] 2024-07-02 04:53
actually this is happened to me when i install from the bin file
because the bin configuration set the start color with orange on the first boot 

even when change the transition time set to 0 it still start with orange then change to preset 

you have to compile your own code to make the start color different

**Comment by blazoncek** [comment] 2024-07-02 05:30
Duplicate of #3196

**Closed** 2024-10-27 17:21 UTC
Labels: fixed in source, workaround, waiting for feedback

**Comment by Andro-Marian** [comment] 2024-10-31 00:46
I flashed the 0.15.0-b6 and when turning off/on the bulbs (7w or 15w) has a weird flicker when using the power putton from the web interface. Not sure why.
