### ISSUE TITLE
WWA LEDs support

### ISSUE THREAD

**Issue by pczekalski** [Aircoookie/WLED#1137] opened 2020-09-02 18:34 UTC
**Is your feature request related to a problem? Please describe.**
At the moment user interface works only for RGB / RGBW led stripes, not for WWB (White Warm, White Cold, Amber).

**Describe the solution you'd like**
A different colour map for WWA LED stripes.

Thank you for your ideas for making WLED better!

**Comment by Code1110** [comment] 2020-11-19 00:32
Possible Duplicate of #552

**Closed** 2022-10-10 07:06 UTC
Labels: enhancement
