### ISSUE TITLE
8266 160MHz /settings/um crash/reboot loop

### ISSUE THREAD

**Issue by spblat** [Aircoookie/WLED#4219] opened 2024-10-23 19:26 UTC
### What happened?

An otherwise stable 8266 running 0.15b6 at 160Mhz crashes and reboots while a web UI is displaying /settings/um . Confirmed by ALDIY @ Discord

Demo https://youtube.com/shorts/lTwzndDkhG0

### To Reproduce Bug

Install 0.15b6 160Mhz build on 8266
Enable AR in Usermods (not sure if this is required to reproduce)
Device goes into a reboot loop

### Expected Behavior

It shouldn’t crash :-)

### Install Method

Binary from WLED.me

### What version of WLED?

0.15.0-b6 (build 2410140)

### Which microcontroller/board are you seeing the problem on?

ESP8266

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dosipod** [comment] 2024-10-23 19:51
Yes that is confirmed from our side also on multiple units , esp8266 with AR on MM seems to be fine  for comparison

**Comment by willmmiles** [comment] 2024-10-24 01:30
While I've opened PR #4222 to fix the general case issue, technically this is already fixed by 26a47537.

**Comment by dosipod** [comment] 2024-10-24 18:52
@spblat We have tested on esp8266 4mb and 2mb , AR is working fine without crashes , please test the same and close this .

**Closed** 2024-10-26 09:35 UTC
Labels: bug, fixed in source
