### ISSUE TITLE
Sporadically color change

### ISSUE THREAD

**Issue by Steude1** [Aircoookie/WLED#2235] opened 2021-09-27 19:28 UTC
Greetings everyone,

I’m very new to the whole "Wled World" and got my first problem in my current Installation, though please don’t judge me for a eventually noob failure.
I would be very thankful for any help about this.
In this Installation I have 6x 2 meters Sk6812 12V Stripes, powered by six 12V 4.2A Nextec Power Supplies and right after the third Stripe some LEDs changes the Color randomly for a short time and changes back to adjusted Color, the Distance between each Stripe is about 10 cm.
The Installation had a short test this morning and I thought at this time everything was running fine, but on the second test this evening the Problem showed up.
The Controller I use is this one https://shop.codm.de/automation/pixel/30/wlan-pixel-controller-wled?c=18, with a 12V-5V voltage converter, the Gnd of everything is connected but actually I have no Capacitors running in the circuit.

Maybe someone could help me to fix this.
Thanks in advance.

**Comment by pbolduc** [comment] 2021-09-28 17:59
Please follow up on discord and close this issue.  Normally the problem is related to ground / wires. But you will get better help on Discord than here.

https://discord.gg/KuqP7NE

**Comment by Steude1** [comment] 2021-09-28 19:04
Ok, thank you very much.

**Closed** 2021-09-28 19:04 UTC
Labels: question
