### ISSUE TITLE
mDNS is not working on 0.13.0

### ISSUE THREAD

**Issue by LowderPlay** [Aircoookie/WLED#2194] opened 2021-09-14 19:09 UTC
**Describe the bug**
mDNS service discovery is broken on 0.13.0 betas. The device can't be reached through its hostname in the browser, resolved using `avahi-browse` or `avahi-resolve` or discovered through the app. 

**To Reproduce**
Install 0.13.0 beta. Try to discover the device in the app, or visit its webpage in the browser.

**Expected behavior**
The device can be successfully resolved in 0.12.0.

**WLED version**
 - Board: ESP8266 (ESP-12F module)
 - Version 0.13.0
 - Format: Binary

**Comment by blazoncek** [comment] 2021-09-14 19:31
Hmm. This is working on 26 of my ESPs.

**Comment by LowderPlay** [comment] 2021-09-15 10:21
I reverted back to 0.12.0 and the discovery worked flawlessly, but when I updated one more time, discovery stopped working for me.

**Comment by blazoncek** [comment] 2021-09-15 10:40
What environment do you run discovery on?

**Comment by LowderPlay** [comment] 2021-09-15 10:57
I tried using the app and `avahi-browse -alr` on a Linux device.

**Comment by blazoncek** [comment] 2021-09-15 11:00
There is a known bug in avahi and ESP implementation.
Can you check Win or mac?

**Comment by LowderPlay** [comment] 2021-09-15 11:20
I'm not sure how to try using it on windows. Could you suggest software that I can use? I tried using java library jmdns on windows, it doesn't work for me on the new version.

**Comment by blazoncek** [comment] 2021-09-15 11:42
Try BonjourBrowser for Windows or similar tool zeroconfServiceBrowser.

**Comment by LowderPlay** [comment] 2021-09-15 11:58
Huh. Weird, I can discover the lights now.

**Comment by blazoncek** [comment] 2021-09-15 12:29
Not weird at all. 😄

**Comment by blazoncek** [comment] 2021-09-29 06:13
Closing as it seems duplicate of #2009

**Closed by blazoncek** 2021-09-29 06:13 UTC
Labels: bug
