### ISSUE TITLE
WLED on another languages

### ISSUE THREAD

**Issue by 04aromeo** [Aircoookie/WLED#2165] opened 2021-08-29 23:43 UTC
I'm Spannish, sorry for the translation.

Hi, I'm thinking about translating the app to different languages. I could translate it to Spanish, French and Vasque, but I need to know how to edit the app texts. Can anyone tell me how to edit? Thanks.

**Comment by blazoncek** [comment] 2021-08-30 12:53
All of the strings are in JS and HTML files inside data folder.
Some strings may be in usermods.

**Comment by neckyaan** [comment] 2021-08-30 15:59
Please refer to：
https://github.com/Aircoookie/WLED/wiki/Add-own-functionality

**Comment by 04aromeo** [comment] 2021-08-30 20:26
> All of the strings are in JS and HTML files inside data folder.
> Some strings may be in usermods.

Oh, thanks, I'm going to try it

**Comment by 04aromeo** [comment] 2021-08-30 20:46
> Please refer to：
> https://github.com/Aircoookie/WLED/wiki/Add-own-functionality

Ohh, that's exactly what I was finding about. Thank you very much! 👍 :)

**Comment by Aircoookie** [comment] 2022-10-21 02:00
Closing as resolved and duplicate of #459

**Closed by Aircoookie** 2022-10-21 02:00 UTC
Labels: enhancement
