### ISSUE TITLE
Feature Request: Option to turn off ESP8266 LED

### ISSUE THREAD

**Issue by mynameisdaniel32** [Aircoookie/WLED#282] opened 2019-10-25 02:33 UTC
I'd love the ability to be able to disable the built-in LED on the ESP8266 boards, it's good to have to know when it's rebooting or reconnecting, but once it's working the LED being on constantly is quite annoying in a dark room.

**Comment by matthiasnowak** [comment] 2019-10-25 07:50
see #18

**Comment by Aircoookie** [comment] 2019-10-25 08:06
Hi! Yes, this is a duplicate of #18. I really need to do something about the number of open issues, no one can be reasonably expected to look through all open issues before submitting a new one :)
Please also see https://github.com/Aircoookie/WLED/wiki/FAQ#how-to-turn-off-the-bright-blue-onboard-led

**Closed by Aircoookie** 2019-10-25 08:06 UTC
