### ISSUE TITLE
OPNSense no uPnP intermittent Wifi connection

### ISSUE THREAD

**Issue by Apprisco** [Aircoookie/WLED#3362] opened 2023-09-08 04:13 UTC
### What happened?

Without uPnP (such as on OPNSense Router), the web gui will take forever to load, and there will be very intermittent wifi connections for certain WLED devices.

### To Reproduce Bug

Disable uPnP in router.
Observe new WLED devices have very intermittent web-gui and app access.

### Expected Behavior

As wLED is LAN based, it should only rely on DHCP or static IP.
uPnP should not be required for WLED, and thus without uPnP, such as for homelab use, WLED should not have intermittent connections.

### Install Method

Binary from WLED.me

### What version of WLED?

0.13.3 & 0.14.0

### Which microcontroller/board are you seeing the problem on?

ESP32

### Relevant log/trace output

```shell
No log output at all.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment] 2023-09-08 04:58
WLED does not use uPnP.
The problem might be in your network set-up.

**Comment by softhack007** [comment] 2023-09-08 20:14
@Apprisco is this the same problem as in your new report 
* https://github.com/Aircoookie/WLED/issues/3363

If yes, should we close this one in favour of the new report?

**Comment by softhack007** [comment] 2023-09-09 19:13
duplicate of  #3363

**Closed by softhack007** 2023-09-09 19:13 UTC
Labels: connectivity, external
