### ISSUE TITLE
WLED Ambilight over USB for Dummies [Solution]

### ISSUE THREAD

**Issue by TarFilarek** [Aircoookie/WLED#1769] opened 2021-02-22 16:20 UTC
Hi!
Some time ago I've opened a thread concerning [WLED Ambilight over USB](https://github.com/Aircoookie/WLED/issues/1482). 

Previously, my Wemos D1 Pro was connected with LED Strip via gpio 3 (RX) in accordance with this line of Your code:
`#define LEDPIN 2  //strip pin. Any for ESP32, gpio2 or 3 is recommended for ESP8266 (gpio2/3 are labeled D4/RX on NodeMCU and Wemos)`
Everything worked great except for the Ambilight. I simply couldn't make it work.

After trying everything I could I've decided to resolder the data cable to gpio 2 (D4) and Ambilight started to work instantly (obviously after re-uploading the code). I don't know if that is common knowledge here, maybe I've missed the note that this gpio won't work with that function, but if not - I think that such a note could be featured in the Wiki to prevent others from making the same mistake as I did.

Once again - Thank You for this amazing project!

All the best
![Przechwytywanie](https://user-images.githubusercontent.com/64553282/108736433-e6be2380-7531-11eb-8186-5ca70f359cc5.PNG)

**Comment by blazoncek** [comment] 2021-03-19 20:25
Not a bug. RX pin (GPIO3) is used for serial connection (receiving Adalight data).
Admittedly this should be noted in the comment.
You can close this issue.

**Closed** 2021-03-20 20:06 UTC
Labels: bug
