### ISSUE TITLE
Flag retain

### ISSUE THREAD

**Issue by InnateEvil** [Aircoookie/WLED#3217] opened 2023-05-24 02:31 UTC
Good time! I ask you to add the option to enable the retain flag.

I have a lot of lamps on esp with WLED firmware.

And I use a smart home device that requires the retain flag to connect and configure MQTT for the first time.

I really like using WLED and I really want to add them to my smart home.

Maybe this feature has already been added, but I couldn't find it, help!!!! Thank you in advance!

**Comment by blazoncek** [comment] 2023-05-24 15:38
Some messages are retained. Some are not.
LWT is also set.

**Comment by InnateEvil** [comment] 2023-05-24 16:34
LWT?

**Comment by blazoncek** [comment] 2023-05-27 13:34
Closing as a duplicate of #2263

**Closed by blazoncek** 2023-05-27 13:34 UTC
Labels: enhancement
