### ISSUE TITLE
Can not turn on LEDS with version above 14.0

### ISSUE THREAD

**Issue by tomlut** [Aircoookie/WLED#3854] opened 2024-03-25 22:07 UTC
### What happened?

I have a Hyperion ambilight set up behind my TV consisting of:

250 LED WS2812 on segment 0, UDP sync interface enabled for main segment
20A 5V power supply (multiple injection points).
Quinled ESP32, data pin GPIO26

Using version 14.0 this **works perfectly**. Syncs with video frames and LEDs on/off control operates as expected.

Using any later version (14.1, 14.2) installed and configured fresh, (to eliminate update json config migration as the cause) the LEDs initially turn on but after turning off the LEDs either via the WLED web interface or the Hyperion interface the LEDs can not be turned back on. 

### To Reproduce Bug

Install 14.1 or later version. 
Turn off LEDs, attempt to turn LEDs back on.

### Expected Behavior

LED control and sync to operate.

### Install Method

Binary from WLED.me

### What version of WLED?

14.1, 14.2

### Which microcontroller/board are you seeing the problem on?

ESP32

### Anything else?

Config file:

[wled_cfg_tv-led-strip.json](https://github.com/Aircoookie/WLED/files/14749941/wled_cfg_tv-led-strip.json)

![Screenshot 2024-03-26 at 09-06-19 Sync Settings](https://github.com/Aircoookie/WLED/assets/10679300/b1e80a15-ec08-4eba-96a7-a016da166c98)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tomlut** [comment] 2024-03-25 22:08
https://github.com/Aircoookie/WLED/issues/3854

**Comment by willmmiles** [comment] 2024-03-29 17:47
OK - I think you can close this as a duplicate of #3720 then.

**Closed** 2024-03-29 18:13 UTC
Labels: bug
