### ISSUE TITLE
number limit for Latitude

### ISSUE THREAD

**Issue by sweethome29** [Aircoookie/WLED#3306] opened 2023-08-04 20:21 UTC
### What happened?

WEB GUI - Settings - Time setup. It is not possible to install Latitude if values are greater than 66.6 . BUT there are cities on 67 68 69 . For example:
https://www.countrycoordinate.com/search/?keywords=murmansk
Please fix this is not a misunderstanding. Thank you

### To Reproduce Bug

nope

### Expected Behavior

nope

### Install Method

Binary from WLED.me

### What version of WLED?

any

### Which microcontroller/board are you seeing the problem on?

ESP8266

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Aircoookie** [comment] 2023-08-04 20:26
Duplicate of #3146
Please track that issue for updates!

**Closed by Aircoookie** 2023-08-04 20:26 UTC
Labels: bug
