### ISSUE TITLE
Support for solid RGBW LED strips

### ISSUE THREAD

**Issue by Def3nder** [Aircoookie/WLED#269] opened 2019-10-18 23:04 UTC
Hi Aircooookie,

thx fir this awesome project - it's amazing! 

I have quite a lot of non-digital LED strips attached to MagicHome Adapters re-flashed with Tasmota. 
Unfortunately beside a simple "color-change" there is no single effect available.

I think some of the effects in WLED would look good on single colour strips as well (like rainbow or breath etc.).

Do you think it would be possible to use WLED with an analogue 3 pin RGB strip (+ the common cathode) ?

The NeoPixelBus library does hide so much so that I could not find the point in the code where the colour(s) is passed to the PIN.

I would love to use WLED for the analogue RGB strips.

Greetings from Berlin,
Def3nder

**Comment by Philje123** [comment] 2019-10-19 08:54
Same for me too! I have 3 Magic home controllers with fixed RGB strips (non-addressable) running some custom MQTT code. But would love them all to be Wled. I really like it.

**Comment by theshadowsvk** [comment] 2019-10-19 09:04
Guys you can't have effects like rainbox on non-addressable strips. Imagine that on electricity level. You can only control each color on whole strip, not single diode without led-IC that controls it.
Just buy addressable strips and you are done, they are pretty cheap.
WLED project is only for addressable led strips, so the neopixelbus library, so the ws2812fx library.

**Comment by Def3nder** [comment] 2019-10-19 22:11
Sure, you can. Just define a WLED strip with a single pixel - all you can do with that can get done with an non-addressable strip, too.

**Comment by Def3nder** [comment] 2019-10-19 22:15
I think the way implementing this could bei tweaking the NeoPixelBus Library to offer another hardwsre type and add the logic to drive the three pins there...
What do you think?

**Comment by theshadowsvk** [comment] 2019-10-19 23:08
That's not the way it works. It can behave like single pixel cause it is analog. It lacks the IC which controls the chip, wled project,neopixelbus library etc sends data to this IC, it is data stream. And one IC cant control the whole led strip if you add one external like ws2811.

**Comment by creativeretail** [comment] 2019-10-20 14:12
This will do what you want:-

http://www.freetronics.com.au/freenfet3

Schematic / PCB files here:-

https://github.com/freetronics/FREENFET3

**Comment by brentbrooks70** [comment] 2019-10-21 20:59
@Def3nder this is a Duplicate of #58 Please see that issue for info on to make this work for you

**Comment by Def3nder** [comment] 2019-10-22 11:33
> @Def3nder this is a Duplicate of #58 Please see that issue for info on to make this work for you

@brentbrooks70 Thx - this looks exactly what I was looking for - I will try it and post my results here for reference.

**Comment by Def3nder** [comment] 2019-10-28 09:30
@Aircoookie : I saw you yesterday on Youtube in the Video-Chat with DrZzs and you mentioned the (analog) RGB strips and asked yourself "Why should anybody want to use analog RGB strips ?".
Normaly you're totally wright: the WS281x or SK6812 strips are way better but there is one big advantage of the old analog ones:

1) they are much brighter when you compare at price level
    you can get a 12V 5m RGBWW strip with 60 Pixel per meter 
   for the same price of a 5V 5m WS2812B strip and the later one
   is far less bright.

So, if you don't want an "effekt light" but rather want to have another lightsource,
this is more effective.

I have a 7m long Aluminium profile attached right below the ceiling in my daughter's room with 12V RGBWW strips in it and the light is as bright as 200W (old) halogen light.
She uses it for reading and additional lighting in gernal and 
I use it (controlled from Home Assistant) to display a color that tells her how much time is left in the morning: green = keep laying in the beed, yellow = time to stand-up, red = time to hurry up and begin with breakfast.

Right now I use Tasmota for this, but WLED is way more cooler !
So my goal is to get WLED running with analog 5-PIN RGBW strip, too.


I made the first tests to get (analog) solid color strips to work and basically is does work (with some restrictions - see below). I made the following insertions in **npbWrapper.h**:
  void Begin(NeoPixelType type, uint16_t countPixels)
  {
  [...]
	**_//init PWM pins
	pinMode(5, OUTPUT);
	pinMode(12, OUTPUT);
	pinMode(13, OUTPUT);
	pinMode(15, OUTPUT);
	analogWriteRange(255);
	analogWriteFreq(880);_**
    }
  }
  **_void SetRGBPWM(uint8_t r, uint8_t g, uint8_t b, uint8_t w)
  {
	  analogWrite(5, r);
	  analogWrite(12, g);
	  analogWrite(13, b);
	  analogWrite(15, w);
  }_**

  void SetPixelColor(uint16_t indexPixel, RgbColor color)
  {
	**_if (indexPixel == 0) //5050 strip is first pixel
	{
		SetRGBPWM(color.R, color.G, color.B, 0);
	}_**
[...]
  }

  void SetPixelColor(uint16_t indexPixel, RgbwColor color)
  {
	**_if (indexPixel == 0) //5050 strip is first pixel
	{
		SetRGBPWM(color.R, color.G, color.B, color.W);
	}_**
[...]
  }

With this the RGBW Color is set to the four ESP PINs, but:

 - the master brightness-slider does not work as expected.

You need to set master brightness to MAX and then choose the color with the RGB color wheel. This way you can get dimmed colors with effect "Solid Color".

But if you want to use other effects they will always run at 100% brightness no matter what is used in the master slider.

I will try to peek the NeoPixel Brightness and multiply it with the RGBW-Values next time ...

**Does anybody have other ideas ?**

**Comment by raoulteeuwen** [comment] 2019-10-28 18:58
> I use it (controlled from Home Assistant) to display a color that tells her how much time is left in the morning: green = keep laying in the beed, yellow = time to stand-up, red = time to hurry up and begin with breakfast.

:-)

**Comment by Aircoookie** [comment] 2019-10-28 23:46
@Def3nder that's a fair point with the higher brightness/lower cost of analog strips!

About the brightness slider not working, this is to be expected since that is handled by the NeoPixelBus driver library. We can easily implement the brightness ourselves though (with this it might even make sense to use 10bit instead of 8bit analog resolution, don't know if that makes a difference). First of all, make a new `byte bright;` var in the top of NpbWrapper.
In the SetRGBPWM then put:

```cpp
uint16_t rt = (r*bright) >> 8;
uint16_t gt = (g*bright) >> 8;
uint16_t bt = (b*bright) >> 8;
uint16_t wt = (w*bright) >> 8;
analogWrite(5, rt);
analogWrite(12, gt);
analogWrite(13, bt);
analogWrite(15, wt);
```

and in the setBrightness just add `bright = b`. 
Hope it works fine! (and I believe i will make analog LED PWM outputs available with a simple #define, making them officially supported)

**Comment by Def3nder** [comment] 2019-11-06 12:45
...I've added the code to a new branch of a fork:
https://github.com/Def3nder/WLED/commit/d1c289b709f0f9137180f8ff02ad5662f363b883

**Comment by mason-xx** [comment] 2019-11-14 16:43
This looks exactly what I need. I have some solid strips already installed and don't need some fancy effects but would love to utilize them via wled. Question is, can I flash this onto some of these controllers? https://github.com/arendst/Tasmota/wiki/MagicHome-with-ESP8285
I managed to compile it with the modification of @Def3nder and was able to flash it via nodemcu flasher. I see the wled hotspot, can connect to it but won't get a proper webif. Do i need to mod the code for the ESP8285 on this controller? These are pretty cheap and come in a nice package, so pretty ideal for the job. Sorry if this might a little oftopic but I'm kinda new to this.

**Comment by Def3nder** [comment] 2019-11-15 10:12
Hi @mason-xx , yes, I do have some of them in use, too.
They run perfectly with the modifies WLED.

There are two basic differenct versions out there: one with RGB only and another one with RGBW.

I have one with RGBW in use - to get the right colors from Alexa there are some additional changes necessary - if you want RGBW to drive, have a look here: https://github.com/Aircoookie/WLED/issues/315

Let me know if you have any problems.

**Comment by mason-xx** [comment] 2019-11-15 18:58
Thanks for the answer @Def3nder I wasn't able to get it up at all and went the esphome route. For the simple task of on/off and color change it works very well. and since I already had 3 of the RGB ones in use it won't justify a new purchase. I'll get back to WLED for the ws812b led ones.

**Comment by gijsje** [comment] 2019-11-17 19:29
I would love to see this included in the basic firmware as i have many analog strips and would love that they can work with the digital ones

**Comment by wesmininger** [comment] 2019-11-21 01:54
> Hi @mason-xx , yes, I do have some of them in use, too.
> I would suggest to get the one with RGBW and IR (U can use them for both RGB and RGBW) - I did get mines here:
> https://www.aliexpress.com/item/32884865866.html
> 
> They run perfectly with the modified WLED.
> 
> There are two basically different versions out there: one with RGB only and another one with RGBW.
> 
> I have some with RGBW in use - to get the right colors from Alexa there are some additional changes necessary - if you want RGBW to drive, have a look here: #315
> 
> Let me know if you have any problems.
Hi Def3nder!
Thanks for answering about the Magichome device, its what I have and I was looking for this info! 
When you say "they run perfectly with the modified WLED" what modification do you mean? do you refer to #315 you mention or some other modifications?

**Comment by gijsje** [comment] 2019-11-23 15:38
> ...I've added the code to a new branch of a fork:
> [Def3nder@d1c289b](https://github.com/Def3nder/WLED/commit/d1c289b709f0f9137180f8ff02ad5662f363b883)

Worked great for me using a H801 controller.
had to change the gpio output.
Thanks for this

**Comment by Def3nder** [comment] 2019-11-25 09:03
Hi @gijsje : this weekend I figured out how to use an IR Receiver with the H801.
Is this interesting for you, too ?

I used this remote: https://www.aliexpress.com/item/32987617960.html 
From the Controller I ripped out the IR Sensor - the PCB is labled so you know the right PINs for Vcc, GND and Signal of the sensor.

Then I connected the sensor to +3.3 , GND and GIOP0:
![image](https://user-images.githubusercontent.com/33399267/69526408-65609580-0f6a-11ea-98b7-541180585892.png)


In the Code (in **NpbWrapper.h**) I disabled the button:  `#define BTNPIN -1`,
changed the IR PIN to 0: `#define IR_PIN  0`
and added the logic for the 40-key Remote in **wled20_ir.ino**.

The complete code is here: https://github.com/Def3nder/WLED

**Comment by jihao** [comment] 2019-12-06 12:29
I love this feature and will test it with my rgbw strip this weekend.
It will be great if this can be merge into aircoookie release.

**Comment by GeorgeIoak** [comment] 2019-12-17 17:35
@Aircoookie You had mentioned earlier in this thread that you were considering adding in @Def3nder code. I have another use case for it and that's with the Novastella 20W flood lights. They are RGBWW and although I haven't opened one up they appear to be very similar to the H801. I was able to flash them and control them with https://github.com/thehookup/E131-MQTT-RGBW-Lights/blob/master/E131RGBW_MQTT_Novostella.ino but that's just test code and doesn't take advantage of controlling WW and CW

**Comment by Def3nder** [comment] 2019-12-18 13:15
Hi @GeorgeIoak , 

according to https://blakadder.github.io/templates/novostella_20W_flood.html the board seems to use these PINs: RPIN: 4, GPIN: 12, BPIN: 14, WPIN: 5, W2PIN: 13.

We would propably need some testing but this should work.

I've just opened a pull request for analog RGBW(W) stripes.


Can you see what kind of ESP board is used ? 
It should be an ESP8266 or ESP8285.

As you flashed it, did you see the amount of flash memory ?

I could compile a version for you with some additional input ...

**Comment by GeorgeIoak** [comment] 2019-12-18 18:04
I know those pins are correct since the Arduino sketch I used has those defined. I haven't broken out CW and WW so I can't confirm that they are correct. [This site](https://esphome-configs.io/devices/novostella-20w/) has a little more information and link to the FCC report which shows a Tuya module but I don't recall that specific one and would have to dig up old notes to see if I have a reference to what looks like that. I could be wrong but in that FCC picture I see an external chip which I believe should be a flash chip and that would indicate a ESP8266 device.

I used tuya-convert to flash these and unfortunately I did not take note of what it reported and these are not easy to get into. Since I have OTA access to it I could try and flash some new code that presents the info on it's web page if you think that will help.

@Def3nder BTW, I didn't have much time but I cloned your repo and tried to compile on a Win10 box running VSCode w/ PIO. Unfortunately I was getting errors but that's happened to me with PIO so I need to dig into my setup and find why it didn't work. The bad thing about the code I'm running on this light is that it doesn't have a firmware update page so the only way to update it now is through Arduino OTA. I'm running some tests now on a Wemos D1 Mini to replicate what I have I have on the light so I can confirm the process will work before I attempt it on the light.

**Comment by GeorgeIoak** [comment] 2019-12-18 18:45
@Def3nder I flashed Tasmota on a 2nd flood light and it reports this:

```
ESP Chip Id | 8566815
Flash Chip Id | 0x1540C8
Flash Size | 2048kB
Program Flash Size | 1024kB
Program Size | 446kB
Free Program Space | 556kB
Free Memory | 30kB
```

**Comment by tonyn0** [comment] 2019-12-31 17:18
New to all of this, but love it! Are there are any inherent limitations for implementing _additional_ outputs using an ESP32?

**Comment by tonyn0** [comment] 2020-01-01 20:28
Baby steps! I just stumbled onto the fact that the ESP32 does _not_ support analogWrite, but found what is needed is ledcWrite. I'm working on this now...

**Comment by Def3nder** [comment] 2020-01-06 09:15
I've just implemented the ESP32 support for the solid RGB(W) stripes last weekend.
It uses the ledc function of the ESP32 framework and works quite well.

The downside is that the .bin grows a lot - uses roughly 80% of the program space with that change.
I will create a PR for the update the next days.

**Comment by tonyn0** [comment] 2020-01-06 12:19
@Def3nder Can you comment on "Are there are any inherent limitations for implementing additional outputs using an ESP32?"?

**Comment by Aircoookie** [comment] 2020-01-06 12:30
@tonyn0 ledc has 16 channels, so ESP32 should be able to control 4 analog RGBW or 5 analog RGB strips hardware wise.

@Def3nder wasn't the utilization at around 77% anyways previously?

**Comment by Def3nder** [comment] 2020-01-06 12:39
Hi @tonyn0 , on an ESP32 nearly all the PINs are PWM-capable and can be used for driving LEDs.
But for what reason do you need more than 5 PINs ?

@Aircoookie , I did not build the ESP32 variant before, I was only supprised to get something in the mid 80th -  this was with ledc and IR-Receive.
Some program space could be saved when de-selecting some of the IR protocols - there are very much IR-Remotes for "Air Conditioners" that use a lot of RAM / Flash mentioned in the header file, but at the first look the #defines for that are in the "IRremoteESP8266.h" and I didn't want to touch a file from an external library. Perhaps there is a way to change this defines without touching the library itself.

**Comment by tonyn0** [comment] 2020-01-06 12:46
@Aircoookie That's awesome.

@Def3nder I'm trying to replace an older (abandoned) PWM controller with four, RGBW outputs.

**Comment by Def3nder** [comment] 2020-01-06 15:25
@Aircoookie I just included the IRremoteESP8266 as "local library" under "src/dependencies" and changed all "SEND_...  defines" to false as well as the ones for Air Conditioners /they are all named for a common function in the header).

This shrinkes the .bin by 11k 😃 - isn't it worth including this library, too?
The actual version 2.7.2 has the advantage to support ESP32, too.

[IRremoteESP8266.h](https://github.com/Aircoookie/WLED/files/4026640/IRremoteESP8266.h.txt)

**Comment by Aircoookie** [comment] 2020-01-06 18:41
@Def3nder awesome! Great that they also added ESP32 support!
Submit a PR if you'd like :)

**Closed** 2020-01-22 16:42 UTC
Labels: discussuion, enhancement, fixed in source

**Comment by Dreamoffice** [comment] 2020-04-07 18:50
@GeorgeIoak 
i have also flashed the Flood lights with WLED but actually the CW-LED are not working. can you give me a hint where to look at?
`//this code is a modified version of https://github.com/Makuna/NeoPixelBus/issues/103
#ifndef NpbWrapper_h
#define NpbWrapper_h

//PIN CONFIGURATION
#ifndef LEDPIN
#define LEDPIN 2  //strip pin. Any for ESP32, gpio2 or 3 is recommended for ESP8266 (gpio2/3 are labeled D4/RX on NodeMCU and Wemos)
#endif
//#define USE_APA102  // Uncomment for using APA102 LEDs.
//#define USE_WS2801  // Uncomment for using WS2801 LEDs (make sure you have NeoPixelBus v2.5.6 or newer)
//#define USE_LPD8806 // Uncomment for using LPD8806
//#define USE_P9813   // Uncomment for using P9813 LEDs (make sure you have NeoPixelBus v2.5.8 or newer)
#define WLED_USE_ANALOG_LEDS //Uncomment for using "dumb" PWM controlled LEDs (see pins below, default R: gpio5, G: 12, B: 15, W: 13)
#define WLED_USE_H801 //H801 controller. Please uncomment #define WLED_USE_ANALOG_LEDS as well
#define WLED_USE_5CH_LEDS  //5 Channel H801 for cold and warm white

#ifndef BTNPIN
#define BTNPIN  0  //button pin. Needs to have pullup (gpio0 recommended)
#endif

#ifndef IR_PIN
#define IR_PIN  4  //infrared pin (-1 to disable)  MagicHome: 4, H801 Wifi: 0
#endif

#ifndef RLYPIN
#define RLYPIN 12  //pin for relay, will be set HIGH if LEDs are on (-1 to disable). Also usable for standby leds, triggers,...
#endif

#ifndef AUXPIN
#define AUXPIN -1  //debug auxiliary output pin (-1 to disable)
#endif

#ifndef RLYMDE
#define RLYMDE  1  //mode for relay, 0: LOW if LEDs are on 1: HIGH if LEDs are on
#endif

//END CONFIGURATION

#if defined(USE_APA102) || defined(USE_WS2801) || defined(USE_LPD8806) || defined(USE_P9813)
 #define CLKPIN 0
 #define DATAPIN 2
 #if BTNPIN == CLKPIN || BTNPIN == DATAPIN
  #undef BTNPIN   // Deactivate button pin if it conflicts with one of the APA102 pins.
 #endif
#endif

#ifdef WLED_USE_ANALOG_LEDS
  //PWM pins - PINs 15,13,12,14 (W2 = 04)are used with H801 Wifi LED Controller
  #ifdef WLED_USE_H801
    #define RPIN 04   //R pin for analog LED strip   
    #define GPIN 12   //G pin for analog LED strip
    #define BPIN 14   //B pin for analog LED strip
    #define WPIN 13   //W pin for analog LED strip 
    #define W2PIN 05  //W2 pin for analog LED strip
    #undef BTNPIN
    #undef IR_PIN
    #define IR_PIN  0 //infrared pin (-1 to disable)  MagicHome: 4, H801 Wifi: 0
  #else
  //PWM pins - PINs 5,12,13,15 are used with Magic Home LED Controller
    #define RPIN 5   //R pin for analog LED strip   
    #define GPIN 12   //G pin for analog LED strip
    #define BPIN 15   //B pin for analog LED strip
    #define WPIN 13   //W pin for analog LED strip 
  #endif
  #undef RLYPIN
  #define RLYPIN -1 //disable as pin 12 is used by analog LEDs
#endif

//automatically uses the right driver method for each platform
#ifdef ARDUINO_ARCH_ESP32
 #ifdef USE_APA102
  #define PIXELMETHOD DotStarMethod
 #elif defined(USE_WS2801)
  #define PIXELMETHOD NeoWs2801Method
 #elif defined(USE_LPD8806)
  #define PIXELMETHOD Lpd8806Method
 #elif defined(USE_P9813)
  #define PIXELMETHOD P9813Method  
 #else
  #define PIXELMETHOD NeoEsp32Rmt0Ws2812xMethod
 #endif
#else //esp8266
 //autoselect the right method depending on strip pin
 #ifdef USE_APA102
  #define PIXELMETHOD DotStarMethod
 #elif defined(USE_WS2801)
  #define PIXELMETHOD NeoWs2801Method
 #elif defined(USE_LPD8806)
  #define PIXELMETHOD Lpd8806Method
 #elif defined(USE_P9813)
  #define PIXELMETHOD P9813Method  
 #elif LEDPIN == 2
  #define PIXELMETHOD NeoEsp8266Uart1Ws2813Method //if you get an error here, try to change to NeoEsp8266UartWs2813Method or update Neopixelbus
 #elif LEDPIN == 3
  #define PIXELMETHOD NeoEsp8266Dma800KbpsMethod
 #else
  #define PIXELMETHOD NeoEsp8266BitBang800KbpsMethod
  #pragma message "Software BitBang will be used because of your selected LED pin. This may cause flicker. Use GPIO 2 or 3 for best results."
 #endif
#endif


//you can now change the color order in the web settings
#ifdef USE_APA102
 #define PIXELFEATURE3 DotStarBgrFeature
 #define PIXELFEATURE4 DotStarLbgrFeature
#elif defined(USE_LPD8806)
 #define PIXELFEATURE3 Lpd8806GrbFeature 
 #define PIXELFEATURE4 Lpd8806GrbFeature
#elif defined(USE_P9813)
 #define PIXELFEATURE3 P9813BgrFeature 
 #define PIXELFEATURE4 NeoGrbwFeature   
#else
 #define PIXELFEATURE3 NeoGrbFeature
 #define PIXELFEATURE4 NeoGrbwFeature
#endif


#include <NeoPixelBrightnessBus.h>

enum NeoPixelType
{
  NeoPixelType_None = 0,
  NeoPixelType_Grb  = 1,
  NeoPixelType_Grbw = 2,
  NeoPixelType_End  = 3
};

class NeoPixelWrapper
{
public:
  NeoPixelWrapper() :
    // initialize each member to null
    _pGrb(NULL),
    _pGrbw(NULL),
    _type(NeoPixelType_None)
  {

  }

  ~NeoPixelWrapper()
  {
    cleanup();
  }

  void Begin(NeoPixelType type, uint16_t countPixels)
  {
    cleanup();
    _type = type;

    switch (_type)
    {
      case NeoPixelType_Grb:
      #if defined(USE_APA102) || defined(USE_WS2801) || defined(USE_LPD8806) || defined(USE_P9813)
        _pGrb = new NeoPixelBrightnessBus<PIXELFEATURE3,PIXELMETHOD>(countPixels, CLKPIN, DATAPIN);
      #else
        _pGrb = new NeoPixelBrightnessBus<PIXELFEATURE3,PIXELMETHOD>(countPixels, LEDPIN);
      #endif
        _pGrb->Begin();
      break;

      case NeoPixelType_Grbw:
      #if defined(USE_APA102) || defined(USE_WS2801) || defined(USE_LPD8806) || defined(USE_P9813)
        _pGrbw = new NeoPixelBrightnessBus<PIXELFEATURE4,PIXELMETHOD>(countPixels, CLKPIN, DATAPIN);
      #else
        _pGrbw = new NeoPixelBrightnessBus<PIXELFEATURE4,PIXELMETHOD>(countPixels, LEDPIN);
      #endif
        _pGrbw->Begin();
      break;
    }

    #ifdef WLED_USE_ANALOG_LEDS 
      #ifdef ARDUINO_ARCH_ESP32
        ledcSetup(0, 5000, 8);
        ledcAttachPin(RPIN, 0);
        ledcSetup(1, 5000, 8);
        ledcAttachPin(GPIN, 1);
        ledcSetup(2, 5000, 8);        
        ledcAttachPin(BPIN, 2);
        if(_type == NeoPixelType_Grbw) 
        {
          ledcSetup(3, 5000, 8);        
          ledcAttachPin(WPIN, 3);
          #ifdef WLED_USE_5CH_LEDS
            ledcSetup(4, 5000, 8);        
            ledcAttachPin(W2PIN, 4);
          #endif
        }
      #else  // ESP8266
        //init PWM pins
        pinMode(RPIN, OUTPUT);
        pinMode(GPIN, OUTPUT);
        pinMode(BPIN, OUTPUT); 
        if(_type == NeoPixelType_Grbw) 
        {
          pinMode(WPIN, OUTPUT); 
          #ifdef WLED_USE_5CH_LEDS
            pinMode(W2PIN, OUTPUT);
          #endif
        }
        analogWriteRange(255);  //same range as one RGB channel
        analogWriteFreq(880);   //PWM frequency proven as good for LEDs
      #endif 
    #endif
  }

#ifdef WLED_USE_ANALOG_LEDS      
    void SetRgbwPwm(uint8_t r, uint8_t g, uint8_t b, uint8_t w, uint8_t w2=0)
    {
      #ifdef ARDUINO_ARCH_ESP32
        ledcWrite(0, r);
        ledcWrite(1, g);
        ledcWrite(2, b);
        switch (_type) {
          case NeoPixelType_Grb:                                                  break;
          #ifdef WLED_USE_5CH_LEDS
            case NeoPixelType_Grbw: ledcWrite(3, w); ledcWrite(4, w2);            break;
          #else
            case NeoPixelType_Grbw: ledcWrite(3, w);                              break;
          #endif
        }        
      #else   // ESP8266
        analogWrite(RPIN, r);
        analogWrite(GPIN, g);
        analogWrite(BPIN, b);
        switch (_type) {
          case NeoPixelType_Grb:                                                  break;
          #ifdef WLED_USE_5CH_LEDS
            case NeoPixelType_Grbw: analogWrite(WPIN, w); analogWrite(W2PIN, w2); break;
          #else
            case NeoPixelType_Grbw: analogWrite(WPIN, w);                         break;
          #endif
        }
      #endif 
    }
#endif

  void Show()
  {
    byte b;
    switch (_type)
    {
      case NeoPixelType_Grb:  _pGrb->Show();  break;
      case NeoPixelType_Grbw: _pGrbw->Show(); break;
    }
  }

  void SetPixelColor(uint16_t indexPixel, RgbwColor color)
  {
    switch (_type) {
      case NeoPixelType_Grb: {
        _pGrb->SetPixelColor(indexPixel, RgbColor(color.R,color.G,color.B));
      }
      break;
      case NeoPixelType_Grbw: {
        #ifdef USE_LPD8806
        _pGrbw->SetPixelColor(indexPixel, RgbColor(color.R,color.G,color.B));
        #else
        _pGrbw->SetPixelColor(indexPixel, color);
        #endif
      }
      break;
    }
    
  }

  void SetBrightness(byte b)
  {
    switch (_type) {
      case NeoPixelType_Grb: _pGrb->SetBrightness(b);   break;
      case NeoPixelType_Grbw:_pGrbw->SetBrightness(b);  break;
    }
  }

  // NOTE:  Due to feature differences, some support RGBW but the method name
  // here needs to be unique, thus GetPixeColorRgbw
  RgbwColor GetPixelColorRgbw(uint16_t indexPixel) const
  {
    switch (_type) {
      case NeoPixelType_Grb:  return _pGrb->GetPixelColor(indexPixel);  break;
      case NeoPixelType_Grbw: return _pGrbw->GetPixelColor(indexPixel); break;
    }
    return 0;
  }

  uint8_t* GetPixels(void)
  {
    switch (_type) {
      case NeoPixelType_Grb:  return _pGrb->Pixels();  break;
      case NeoPixelType_Grbw: return _pGrbw->Pixels(); break;
    }
    return 0;
  }


private:
  NeoPixelType _type;

  // have a member for every possible type
  NeoPixelBrightnessBus<PIXELFEATURE3,PIXELMETHOD>*  _pGrb;
  NeoPixelBrightnessBus<PIXELFEATURE4,PIXELMETHOD>* _pGrbw;

  void cleanup()
  {
    switch (_type) {
      case NeoPixelType_Grb:  delete _pGrb ; _pGrb  = NULL; break;
      case NeoPixelType_Grbw: delete _pGrbw; _pGrbw = NULL; break;
    }
  }
};
#endif
`

**Comment by Dreamoffice** [comment] 2020-04-07 18:51
@GeorgeIoak 
i have also flashed the Flood lights with WLED but actually the CW-LED are not working. can you give me a hint where to look at?

**Comment by GeorgeIoak** [comment] 2020-04-07 20:14
@Dreamoffice I still don't have WLED on these lights. You'll have to ask nicely to @Def3nder to see if he has time. The last time we spoke he was going to order one of the lights

**Comment by roboraptor** [comment] 2021-02-21 00:14
It is wery nice to jump into already going train like this! 

I just finally repaired an EGLO light with CWRGB leds.
Salvaged their bluetooth driver and replaced with esp8266 flashed with tasmota.
After few minutes fiddling with it through webUI and Alexa I was like "Damn! that is boring..." 
Wondering if something like WLEDs effects could take place and change the colors at itself instead of me still clicking on the colorwheel.

And here I am. 😄 Looking forward for this part to continue.
