### ISSUE TITLE
Unable to save LED Swap Setting

### ISSUE THREAD

**Issue by MarcusinCO** [Aircoookie/WLED#3500] opened 2023-11-02 14:36 UTC
### What happened?

config -> LED Preferences -> output 1

Set to Sk6812 RGBW, color order BRG.  If I select swap and "W & B" it, shows in the drop down.  I click save, but it does not save this feature.  

### To Reproduce Bug

Set to Sk6812 RGBW, color order BRG.  If I select swap and "W & B" it, shows in the drop down.  I click save, but it does not save this feature.  

### Expected Behavior

swap setting is saved.

### Install Method

Binary from WLED.me

### What version of WLED?

14 (also tried on 14b6 and 13.3)

### Which microcontroller/board are you seeing the problem on?

ESP32

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blazoncek** [comment] 2023-11-02 14:49
Duplicate of #3094. Also see #2646.
Closing.

**Closed** 2023-12-14 19:12 UTC
Labels: bug, duplicate
